### ISSUE TITLE
[FEATURE] Shared vision based on token disposition

### ISSUE THREAD

**Issue by patrickburk1988** [CDeenen/SharedVision#10]
**Is your feature request related to a problem? Please describe.**
My players have `None` permissions for every actor but their own, but I'd still like them to be able to share vision. Enabling `Actor permission: None` in the module settings, however, also shares the vision of NPC tokens (including those that are hostile!).

**Describe the solution you'd like**
It'd be cool if there were a way to additionally filter shared vision based on actors' dispositions — perhaps checkbox settings like `Actor disposition: Friendly`, `Actor disposition: Neutral` and `Actor disposition: Hostile`?

**Describe alternatives you've considered**
This is definitely a nonessential feature request! I can easily circumvent the problem by either A) enabling `Global Shared Vision` for friendly actors, or B) enabling player actors to share with every other player actor. Adding this feature, however, would make it a global thing that removes the need to change individual actor settings.

**Comment by CDeenen** [comment]
This has been added in the latest version
