### ISSUE TITLE
[BUG] Actor configuration dialog won't save and apply correctly.

### ISSUE THREAD

**Issue by the-real-orson** [CDeenen/SharedVision#13]
**Setup**
 - OS: Windows 10
 - Browser: Chrome
 - Module version: 1.0.7
 - Foundry version: 9.245
 - Gaming system & version: dnd 5e 1.5.7
 - Any other modules enabled: [yes/no] yes

**Describe the bug**
Right clicking on an Actor to set Shared Vision from Actor's drop down.  Window opens, and I see a list of players with corresponding checkbox.  If I check the first checkbox, the vision is shared correctly.  However, if I deselect the first checkbox and choose the second Player, after I save that configuration the appropriate player isn't sharing vision...and, when I reopen the dialog for the same actor the FIRST PLAYER is selected, not the second player in the list.  This behavior occurs when I select any player other than the first in the list.  I can; however, have persistent checkage of the second player IF the first player is also checked.  For the third player, the two above them must be checked....and so on.  

**Screenshots**

**Console Log**
No errors in the console

**Additional context**

**Comment by CDeenen** [comment]
Thanks for the bug report. 
I can reproduce this. I'll look into fixing it asap.

**Comment by the-real-orson** [comment]
sweet!

**Comment by CDeenen** [comment]
Sorry it took so long, but this should now be fixed
