### ISSUE TITLE
[Feature Request] Share revealed fog of war

### ISSUE THREAD

**Issue by TaakoMagnusen** [CDeenen/SharedVision#15]
**Describe the Feature**
When a token which is sharing vision with another moves into an unexplored area, and then moves out of that area so the fog of war is revealed but dimmed, the revealed area is not shared with other tokens. Thus, if one member goes far up ahead of the party the party can only see the scouting players current vision, and not the previous landscape that token had seen.

**Screenshots**
Imagine a scenario where one player is locked in a store room and the other is looking for a key.
https://i.imgur.com/cDCtVfo.png

The Halfling rogue goes south and west revealing a hallway and a door, the elf wizard (trapped in the store room) can see the hallway as its currently in the halfling rogues active vision area
This is the correctly displayed on the Elf players screen: https://i.imgur.com/YAR6590.png

Now the Rogue goes back where they came from a few steps, making that door and area to the south no longer part of their active vision area, but it is still a revealed section of the Fog of War
The Rogue can see this dimmed area https://i.imgur.com/Sy3ADgZ.png
**BUT the elf wizard sees it as if it were fog of war that has never been revealed**: https://i.imgur.com/yamMGct.png

Additionally in the screenshots you can notice that the area right below the store room is in a similar situation, it is revealed as "previously explored area" for the rogue but for the elf its black fog of war.

It would a great feature to be able to share revealed fog of war between players.

**Comment by CDeenen** [comment]
Fog of war is now shared
