### ISSUE TITLE
[FEATURE] Share token location but not sight

### ISSUE THREAD

**Issue by GhostwheelX** [CDeenen/SharedVision#18]
Might it be possible to share token location, rather than full vision, with other players?

For example, if the characters are in a dungeon and one goes around a corner, I would like the other players to know where that character's token is, though not be able to see everything they can see, if you understand what I mean. Let me know if I'm not explaining well, and I'll try to clarify.

Edit: Same for pets and the like that are assigned to a character.

**Comment by CDeenen** [comment]
I think I understand what you're looking for. There is already a different module that can do that: [Shared Token Visibility](https://foundryvtt.com/packages/shared-token-visibility). I don't know if it still works, though. Please give that a try, and if there's issues with it, let me know, and I'll consider adding it to Shared Vision.

**Comment by GhostwheelX** [comment]
Yep, that's one that I've used in the past. Unfortunately, it's been non-functional for a long while now, or I would use it.

Whenever I use the above module, the entire canvas goes gray and doesn't show anything. I've tried Find the Culprit, and even when it's the only module active, it still does that. I think the author has abandoned it, unfortunately.

**Comment by CDeenen** [comment]
Alright, I'll see what I can do.

**Comment by CDeenen** [comment]
This has been added in the latest version. Go to the actor's Shared Vision config, and enable 'Token'
