### ISSUE TITLE
[BUG] Module no longer works at all

### ISSUE THREAD

**Issue by mkevans80** [CDeenen/SharedVision#19]
After updating the module, it appears to be completely nonfunctional.  I can enable or disable it in the "Manage Modules" menu but otherwise it is as if the module doesn't exist.  When the module is enabled, there is no entry for it in the "Configure Module Settings" menu, no options under the actors tab, no button to toggle shared vision... nothing!  

When I go back and reinstall the older version, everything works again... though I will say it has been wonky the last few weeks.  By wonky, I mean that sharing global vision will let my token see the map area that friendly vision-sharing tokens can see, but not any actors, including the vision sharers.  I don't know whether an update to the 5e system broke it or what... I only noticed it during a game I was running when one of my players could no longer see the tokens he should be able to.

**Setup**
 - OS: Mac OS Monterey 12.4
 - Browser: Vivaldi, Chrome
 - Module version: 1.0.8
 - Foundry version: Forge Version 9
 - Gaming system & version: dnd 5e 1.6.3
 - Any other modules enabled: no

**Comment by CDeenen** [comment]
Thanks for your report. Apparantly I messed something up with the last update that broke the module for Forge users. I've just pushed another update and I've checked that it works on the Forge.

If I understand the other issue you mentioned, you mean that when you select specific players to share vision to in the Shared Vision config (by right-clicking an actor), vision isn't always shared properly, while the 'global vision' setting does. If that's the case, this should be fixed. Otherwise, please open a new issue, thanks!

**Comment by mkevans80** [comment]
Works great now, thanks!  I used Find the Culprit to determine that the other issue I was having is caused by the “Levels" module.  The best way I can describe the issue is this:  If Actor A is sharing vision with Actor B,  B can see all the parts of the map that A can see, with no problem.  However, B cannot see any actors/tokens on the map that only A can see… including A’s token.  B can see the map background, but it’s otherwise empty.  This happens regardless of what level actor A and B are on.  It’s very weird.  Fortunately, I use the Level mod very sparingly, so I can keep it off the vast majority of the time.

My game group adores the module, btw…  My players often comment that they can’t imagine how we ever managed without it before.  Thank you for your work!

**Comment by CDeenen** [comment]
Happy to hear that you and your group like the module so much!
Levels is known to be incompatible. I might get around to that at some point, but it's not a high priority for me.
