### ISSUE TITLE
[Improvement suggestion] Combat-only operation

### ISSUE THREAD

**Issue by lucaspicerni** [CDeenen/SharedVision#21]
Hi! Could you please implement an option so that the module is only active during combat? Grateful!

**Comment by CDeenen** [comment]
This has been added in the latest version. In the module settings, there's not a configuration button to open up all the module configuration. At the bottom there's a 'Combat' section, there you can specify what to do when combat starts and ends.
In your case, set 'Disable All Vision Sharing' to disable for start and enable for end.
