### ISSUE TITLE
[BUG] Create Actor freezes with SharedVision enabled

### ISSUE THREAD

**Issue by Falerion-git** [CDeenen/SharedVision#23]
I experience problems with creating new actors when the SharedVision module is enabled. 

Founrdy v10.284
SharedVision 1.1.1
libWrappr 1.12.8.0

With SharedVision turned on, lets me open the "Create New Actor" window, but as soon as i hit "Create New Actor" foundry freezes. I have to restart the browser tab.
If I deactivate SharedVision, the problem vanishes.

**Comment by CDeenen** [comment]
What gaming system are you on? I tried to replicate it with dnd5e, but it's working fine for me.
Do you have any other modules besides Shared Vision and libWrapper enabled?

**Comment by Falerion-git** [comment]
I used DnD52 2.0.2.
I restarted my server and after that the problem is gone. I can't reproduce it anymore with the SharedVision module, instead it's now with another module. I had the other module also installed before I tried out SharedVision. I guess it already crashed the app. 
Can be closed.
