### ISSUE TITLE
[BUG] Incompatible with Midi QOL on Foundry v10

### ISSUE THREAD

**Issue by webmaster94** [CDeenen/SharedVision#24]
**Setup**
OS: Windows (using node.js server)
Browser: Chrome
Foundry Virtual Tabletop: Version 10, 10.284
Game System: dnd5e, 2.0.2
Midi QOL Version: 10.0.9
Shared Vision Version: 1.1.1

Error:
![image](https://user-images.githubusercontent.com/85364225/189156169-caf1ec5f-10d1-4010-a9ab-43a228842528.png)
Symptom: Canvas loads but no image is displayed
I attempted to prioritize either Midi QOL or Shared Vision in LibWrapper with no change. Both modules worked without issue in Foundry v9. Thankfully I am not using v10 until I can establish full module compatibility but I thought it prudent to report the issue. I will also be submitting the same issue to Midi QOL's repository.

**Comment by tposney** [comment]
It looks like the midi override is using a very old version of the code.

Here's what midi does now:
```js
function _isVisionSource(wrapped) {
  const isVisionSource = wrapped();
  if (this.document.hidden && !game.user.isGM && this.actor?.testUserPermission(game.user, "OWNER")) {
    return true;
  }
  return isVisionSource;
}
```
The wrapped arg is what libWrapper passes in. It just calls the original function.

**Comment by CDeenen** [comment]
Thanks for the bug report. I'll have a look at fixing it after the weekend.

**Comment by MrVizious** [comment]
Can confirm it happens to me too, and got to the same conclusion as @tposney about where the error originates from

**Comment by CDeenen** [comment]
It took a bit longer than I planned, but this should be fixed in the latest update
