### ISSUE TITLE
[BUG] When Global Shared Vision is enabled the GM can no longer see everything

### ISSUE THREAD

**Issue by Zamrod** [CDeenen/SharedVision#26]
**Setup**
 - OS: Windows 11
 - Browser: Foundry App
 - Module version:1.1.1
 - Foundry version: 10.285
 - Gaming system & version: dnd5e 2.0.2
 - Any other modules enabled: no
 - 
**Describe the bug**
If Global Shared Vision is enabled and the GM has no tokens selected they can only see what the tokens that are sharing their vision can see and not everything like they'd normally be able to.

Also, if you select any token that isn't sharing its vision as GM you still see all the shared vision in addition to the token's vision.

**Screenshots**
With the module disabled or with Global Shared Vision disabled:
![image](https://user-images.githubusercontent.com/12570777/190843863-7f8550dd-168d-4ae4-a185-af9dac432897.png)

With it enabled:
![image](https://user-images.githubusercontent.com/12570777/190843892-0fbf16a0-9cc5-4cdf-99d0-cc7a05ab75b4.png)

**Additional context**
I think if you select one of the tokens that are sharing their vision, you should see their shared vision but not if you select any other token or when you have no tokens selected.

**Comment by ntebben** [comment]
This is exactly the behavior I came here to report as well. Note that this happens anytime the GM has ANY shared vision from a token, it restricts the GM's vision to only the tokens that have shared vision with the GM. The module used to work perfectly where selected tokens would show all vision they had, shared and native, and then go back to full map visibility when the GM selected no tokens. This no longer happens on 9.280 either.

**Comment by Jensenator360** [comment]
Same for my Dungeon World game. I needed to disable Shared Vision so that I can see the monster tokens.

**Comment by CDeenen** [comment]
Something went wrong when I tried to add the option to share vision for the GM. I haven't figured out why this happens, so I've removed that feature for now.
I've just pushed an update that should fix this.
