### ISSUE TITLE
Hidden tokens still have and share vision

### ISSUE THREAD

**Issue by hulien22** [CDeenen/SharedVision#4]
Usually when a token is hidden, the player no longer has any vision from that token (this is useful for moving players across the map without revealing stuff in between point A and point B). I noticed that after enabling the SharedVision module that this is no longer the case. Furthermore, if I enable global shared vision, then other players would also still be able to see through a hidden token.

Repro 1 (one token):
- Player A has ownership of Token A. 
- GM hides Token A (right click token, click on hide)
- Notice that Player A is still able to see from where Token A is, despite the fact that the token is now hidden

Repro 2 (two tokens):
- Player A has ownership of Token A, and Player B has ownership of Token B
- Both Token A and Token B have Global Shared Vision enabled in their permission config
- GM enables global shared vision via the control button.
- GM hides Token A.
- Notice that both players are still able to see via the hidden token

_I will note that I do have MidiQol installed, however I do not have the `playerControlsInvisibleTokens` setting enabled, so I don't believe this has an impact on the issue(?)_

I was able to fix this locally for my game by adding in a `if (this.data.hidden) return false;` at the top of `isVisionSourceOverride()`.

**Comment by CDeenen** [comment]
Thanks for reporting this in such detail!
It was a conscious decision to allow the vision to be shared, even if a token is hidden. The main reason is that you could use a hidden token to reveal areas without a PC being there, almost like a sort of light source. I thought this would mainly be useful for the global vision setting, so you easily could show a whole area, even if the PCs do not have full visibility.

I can understand that this is not always preferable, so I'll make it a toggleable setting.

**Comment by CDeenen** [comment]
This has been added in v1.0.3 that can be downloaded right now
