### ISSUE TITLE
[BUG] Shared Vision Tokens don't reveal Roofs

### ISSUE THREAD

**Issue by GambetTV** [CDeenen/SharedVision#5]
The latest version of Foundry let's you mark tiles as Overhead Tiles, so that when you move a token beneath it, the image will go transparent so you can see beneath it. Unfortunately this doesn't seem to occur with tokens that have Shared Vision active, but no ownership of the token.

**Comment by CDeenen** [comment]
Sorry for the late response, but I've just fixed this in v1.0.5
