### ISSUE TITLE
[BUG] Canvas fails to load with hidden token

### ISSUE THREAD

**Issue by Nopants** [CDeenen/SharedVision#7]
**Setup**
OS: Windows
Browser: Chrome
Module version: 1.0.5
Foundry version: 0.8.7
Gaming system & version: Shadowrun 5th Edition 0.7.17 / dnd5e 1.3.5
Any other modules enabled: no

**Describe the bug**
When a token with Shared Vision (independent from Share Hidden checkbox) gets hidden, the canvas fails to load on the players side. When unhidden, canvas will work again on reload. If you log in as a GM through the Foundry App or Chrome, everything works fine. There seems to be a dependence on midiQOL.

I just tested this behavior in dnd5e with midiQOL (and DAE) installed: Same result.

**Console Log**
![image](https://user-images.githubusercontent.com/886406/122740553-61027880-d284-11eb-8077-742203da1b8a.png)

**Comment by CDeenen** [comment]
Thanks for catching another bug, I've just pushed a fix (v1.0.6)
